### ISSUE TITLE
Please use protonDB.svg instead of React Icons logo

### ISSUE THREAD

**Issue by vrman123** [OMGDuke/protondb-decky#1]
[protondb-decky](https://github.com/OMGDuke/protondb-decky)/[src](https://github.com/OMGDuke/protondb-decky/tree/main/src)/[components](https://github.com/OMGDuke/protondb-decky/tree/main/src/components)/protonMedal.tsx should probably use https://www.protondb.com/sites/protondb/images/site-logo.svg instead of <SiProtondb size={20} /> (line 76)

currently attempting a fork and then PR :)

**Comment by vrman123** [comment]
PR #2 made, merge if you want

**Comment by OMGDuke** [comment]
Merged
