### ISSUE TITLE
Font, text style, icon style does not reflect ProtonDB

### ISSUE THREAD

**Issue by EMERALD0874** [OMGDuke/protondb-decky#12]
If you agree with and want help with this, please let me know and I can make a fork/PR.

- Font should be changed to [Abel](https://fonts.google.com/specimen/Abel).
- Summary text should be capitalized.
- Summary text should be centered within its div.
- ProtonDB logo should be black to be more consistent with the icons displayed on the website (personal opinion).

![image](https://user-images.githubusercontent.com/11338953/184688834-5e872c6a-8b1a-4018-a421-0ce10b1a85cf.png)

**Comment by EMERALD0874** [comment]
Discussed over Discord. I'm beginning work on a PR now.

**Comment by OMGDuke** [comment]
Appreciate it. Thanks for the improvements!
