### ISSUE TITLE
Change to using inline SVG instead of base64

### ISSUE THREAD

**Issue by OMGDuke** [OMGDuke/protondb-decky#15]

**Comment by OMGDuke** [comment]
@EMERALD0874 @vrman123

**Comment by vrman123** [comment]
after the discussion in the discord, i think (as AAGaming said), inline css is our best choice.
it'll probably be a bit of effort to scale/position it correctly, but afterwards it should be more useful.

**Comment by OMGDuke** [comment]
I don't really have a preference between react-icons react logo or an inline svg. 

react-icons are pretty easy to style and size so maybe let's go with that unless anyone has strong feelings? I think @EMERALD0874 has already started implementing that

**Comment by OMGDuke** [comment]
Looks like react-icons render out to inline svg anyway

**Comment by vrman123** [comment]
I just tried it to see how hard it was and it wasn't too hard to add inline svg, I just took the svg from https://www.protondb.com/sites/protondb/images/site-logo.svg and added width to the <svg>....

Either way is fine, I just don't love the square black box of the react-icon

**Comment by OMGDuke** [comment]
> I just tried it to see how hard it was and it wasn't too hard to add inline svg, I just took the svg from https://www.protondb.com/sites/protondb/images/site-logo.svg and added width to the ....
> 
> Either way is fine, I just don't love the square black box of the react-icon

I think @EMERALD0874 found the react logo is the same image as the protondb logo

**Comment by vrman123** [comment]
Oh I see, I was confused. @EMERALD0874 was suggesting the react-icon for the *react* logo, not the same protonDB one...
Yeah i think that's probably fine, woops.

**Comment by EMERALD0874** [comment]
Fixed and testing now. You can assign this issue to me.
