### ISSUE TITLE
When using a controller to select the badge sometimes the play button gets reselected on its own

### ISSUE THREAD

**Issue by OMGDuke** [OMGDuke/protondb-decky#20]
Weird one that I haven't been able to delve into yet.

If you go to a game page and immediately press up to get to the badge, the play button will instead get selected about a second later.

After this you can freely select the badge again without having the selector move on its own.

Also if you wait upon arriving on the page page it does not change after selecting the badge

**Comment by ManedCalico** [comment]
Hey there,

I know this is an older issue, but wanted to point out that this isn't isolated to just the protondb badges. This behavior also occurs with the HLTB plugin with "view details" enabled. You're probably already aware of this, but figured it was worth mentioning anyway.

Thanks!

**Comment by OMGDuke** [comment]
Fixed in #81
