### ISSUE TITLE
Add a Custom Attribute with the tier color so each tier can be themed

### ISSUE THREAD

**Issue by joamjoamjoam** [OMGDuke/protondb-decky#24]
Is it possible to add a custom attribute or class that contains the tiers and if the game has a native Linux version so you can theme the protonDB Medal?

Ex. Change the elements background colors per tier, Color the Proton Logo based on tier etc.

**Comment by OMGDuke** [comment]
Yep. I'll get that done for the first release and document them

**Comment by joamjoamjoam** [comment]
Sweet Thanks!

**Comment by OMGDuke** [comment]
`protondb-decky-indicator-${protonDBTier}` platinum gold borked etc
`protondb-decky-indicator-native` if native

I'm adding these to the <Button />

Does that work for you @joamjoamjoam ?

**Comment by OMGDuke** [comment]
Now in main https://github.com/OMGDuke/protondb-decky/pull/25
