### ISSUE TITLE
Adjustable Badge Position

### ISSUE THREAD

**Issue by OMGDuke** [OMGDuke/protondb-decky#4]
Allow user to change position of the badge in the header with a QAM control

**Comment by joamjoamjoam** [comment]
This could easily be handled by using a CSS Loader Theme if you want it to be user configurable. it would be nice to have this built into the plugin too though. Even if its just a top right bottom right type of thing.

**Comment by joamjoamjoam** [comment]
here's a quick and dirty theme using CSSLoader to implement this and the opacity change when the medal is selected. 
Can make selection in the CSS Loader theme UI.

https://github.com/joamjoamjoam/SteamDeckThemes

**Comment by OMGDuke** [comment]
I was just going to build it into the plugin config for now, top-left, top-right, bottom-left, bottom-right.

But yeh there's a css class on the component so anyone could add additional themes themselves via CSS Loader

**Comment by joamjoamjoam** [comment]
Yeah sounds like a good plan.

**Comment by OMGDuke** [comment]
https://github.com/OMGDuke/protondb-decky/pull/25
