### ISSUE TITLE
Valid Games without ProtonDB reports dont show a pending badge

### ISSUE THREAD

**Issue by joamjoamjoam** [OMGDuke/protondb-decky#5]
Games like Feudal Alloy (appId: 699670) have valid steam app ids but have no reports so the API call returns them as an empty json array. These should probably show a pending status badge.

**Comment by OMGDuke** [comment]
AppId's without any reports return as 404 on the protondb api
https://www.protondb.com/api/v1/reports/summaries/699670.json

Using the unofficial api gives an empty array, but it also returns an empty array for invalid appId's (non steam games)
https://protondb.max-p.me/games/699670/reports/

I'll have to see if there's a way to see if its a steam game vs non steam game, steam games can be treated as valid appIds and show pending. Non steam appIds will be ignored for now (https://github.com/OMGDuke/protondb-decky/issues/3)

**Comment by OMGDuke** [comment]
`appStore.GetAppOverviewByGameID(appId)`

Looks like `app_type` reports 1 for steam games 👍

**Comment by OMGDuke** [comment]
https://github.com/OMGDuke/protondb-decky/commit/18a695fe18845d01cee15bf55b234ac2c6090212

Fixed in this commit on the staging branch

**Comment by joamjoamjoam** [comment]
Sweet the app ids for non steam games are always > 0x02000000. The calcsfkr non steam game app ids is crc32(exe + appname) + "02000000"  might be able to save an api call.
