### ISSUE TITLE
Add Multi-Language Support

### ISSUE THREAD

**Issue by ThomasEricB** [OMGDuke/protondb-decky#51]
Please consider adding a way to change language/ or to support other languages, so people like me could translate this plugin to other languages like Portuguese. Thank you, Thomas.

**Comment by OMGDuke** [comment]
Agreed makes sense. I'll try to find some time this weekend

**Comment by OMGDuke** [comment]
https://crowdin.com/project/protondb-decky

Plugin now supports localisation based on the language set in steam deck settings, defaulting to English if the language is not supported

**Comment by ThomasEricB** [comment]
@OMGDuke Thank you!!! I just finished translating Brazilian Portuguese based on the Proton DB's Brazilian Portuguese translation...

**Comment by OMGDuke** [comment]
Thanks very much, I appreciate it! Will go live in the next update which I'm preparing now!

**Comment by OMGDuke** [comment]
Apologies, I had to redo the Github integration as it wouldn't let me change the branch it was targeting. (First time using Crowdin) I've had to reupload your translations but your name is no longer beside them. I'm really sorry! Didn't want you to think I'd removed it on purpose.

Just trying to work out how to get Crowdin to export with the proper file names for Portugal and Brazil Portuguese  and then I'll get the update ready

**Comment by ThomasEricB** [comment]
Don't worry!

**Comment by ThomasEricB** [comment]
@OMGDuke By the way, Brazilian Portuguese and European Portuguese should be their own categories since the words they use are vastly different from ours here in Brazil.

**Comment by OMGDuke** [comment]
> @OMGDuke By the way, Brazilian Portuguese and European Portuguese should be their own categories since the words they use are vastly different from ours here in Brazil.

Yeh, currently crowdin is trying to export them both as pt so trying to separate out topt and  pt-br as that's what the steam deck uses
