### ISSUE TITLE
Minimalist to Regular Expand on Hover Option

### ISSUE THREAD

**Issue by ManedCalico** [OMGDuke/protondb-decky#52]
Hello,

I'm finding that I like the style and readability of the regular badge when checking a game's ProtonDB rating, but I also want the less obtrusive minimalist badge the rest of the time. The expand on hover option is a fantastic feature, but I don't prefer the small badges.

Would it be possible to add an additional on-hover option to expand the minimalist badge into a regular badge instead?

![Example](https://user-images.githubusercontent.com/115047089/221351648-73cb2089-8ae6-482e-8e66-51a7fc662029.png)

Thanks!

Edit: Sorry, I'm still new to GitHub and not sure how to add a label...

**Comment by ManedCalico** [comment]
Sorry, I'm still new to GitHub and not sure how to add a label...

**Comment by OMGDuke** [comment]
Sure I can look into this

**Comment by ManedCalico** [comment]
Thank you!!

**Comment by OMGDuke** [comment]
This will go live with the next release

**Comment by ManedCalico** [comment]
You're awesome!!
