### ISSUE TITLE
Show an extra Native badge if there is a Linux native version of the game.

### ISSUE THREAD

**Issue by joamjoamjoam** [OMGDuke/protondb-decky#6]
If a game has a native linux version add a native metal as well as the tier medal.

**Comment by OMGDuke** [comment]
I don't think either of the APIs return if the game is native.

https://www.protondb.com/api/v1/reports/summaries/337000.json
https://protondb.max-p.me/games/337000/reports/

Any other APIs you're aware of?

**Comment by EMERALD0874** [comment]
You might be able to use this ProtonDB API which is a proxy for the Steam web API.
Dragon Drop, native to Linux - https://www.protondb.com/proxy/steam/api/appdetails/?appids=1581500
Minecraft Dungeons, not native to Linux - https://www.protondb.com/proxy/steam/api/appdetails/?appids=1672970

`{ID}.data.platforms.linux` should always return a boolean representing whether or not the game is native to Linux.

**Comment by OMGDuke** [comment]
Thanks @EMERALD0874 That works great.

![image](https://user-images.githubusercontent.com/17005532/184553477-5dc4eebe-91cd-4e01-865e-aa8cc2ecbf2c.png)

**Comment by OMGDuke** [comment]
https://github.com/OMGDuke/protondb-decky/commit/7875183151c32892aabef296f0017fc0160ec4f5
