### ISSUE TITLE
Add some indication that the the protonDB medal is selected.

### ISSUE THREAD

**Issue by joamjoamjoam** [OMGDuke/protondb-decky#7]
Its hard to see that the tier medal is selected since it has no UI change when "active".

The "active" element is any element with the classes gpfocus and gpfocuswithin.

Something simple will do like changing the opacity slightly using CSS.

This could easily be handled by using a CSS Loader Theme if you want it to be user configurable.

**Comment by OMGDuke** [comment]
Using Button from `decky-frontend-lib` now gives a border to the button when selected by gamepad

Unselected 
![image](https://user-images.githubusercontent.com/17005532/184541656-dc556f5f-4e41-4da0-994d-9f4d797f686d.png)


Selected
![image](https://user-images.githubusercontent.com/17005532/184541662-600f721a-e331-4066-8c2f-06255a381365.png)

This is now on main

**Comment by joamjoamjoam** [comment]
Border looks good

**Comment by OMGDuke** [comment]
An opacity/brightness change like you said might be good as well, Need to work out how to get .css files working with rollup so I can do that based on the .gpfocus class

**Comment by joamjoamjoam** [comment]
I asked the decky guys about this earlier and theu said loading external css files will be supported later. They said only inline was supported for now. Let me know if you find a workaround for it.
