### ISSUE TITLE
Badge Position and Size Unable to Change

### ISSUE THREAD

**Issue by LightningMarshal** [OMGDuke/protondb-decky#74]
Unable to adjust the default size and position of the badge on system  beta channel OS version 3.5.7 build 20231122.1

Badge displays correctly as expected, however adjustments in the settings do not render any changes and for example selecting badge position top right does not persist after selected.

However, badge size and position is adjustable on stable update channel. When changes are made on stable update channel to positioning or size and then the update channel is changed to beta, the changes made persist.

Not a major issue right now, but wanted to document if what ever is breaking on the beta channel is pushed to main.

**Comment by OMGDuke** [comment]
Thanks for the report. Will verify and work on a fix.

**Comment by L0WR1D3Rz** [comment]
I confirm that to date the settings/options don't work. We get regular sized badges on the top left no matter what setting we pick.

**Comment by mirfalltnixein** [comment]
The beta version of SteamOS was now pushed to live, meaning this issue will be actively impacting everybody now.

**Comment by OMGDuke** [comment]
> The beta version of SteamOS was now pushed to live, meaning this issue will be actively impacting everybody now. 

Thanks, I've got the fix merged in. I'll create the release and submit to the store when I'm home this evening

**Comment by OMGDuke** [comment]
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/517

Update to fix this is  submitted to the store. Once it's available I'll close this issue

https://github.com/OMGDuke/protondb-decky/releases/tag/v1.0.12

**Comment by OMGDuke** [comment]
v1.0.12 is on the testing store. I've changed the way settings are saved so your settings will reset when you first update.

This fixes the issues with not being able to change settings for the plugin

**Comment by OMGDuke** [comment]
Fix available on the main store. Closing
