### ISSUE TITLE
DFL needs a bump due to complete breakage in new Steam Client

### ISSUE THREAD

**Issue by HugLifeTiZ** [OMGDuke/protondb-decky#78]
[See this specific comment](https://github.com/SteamDeckHomebrew/decky-loader/issues/597#issuecomment-1987138946) of SteamDeckHomebrew/decky-loader#597. Thanks for your time.

**Comment by OMGDuke** [comment]
This plugin uses global DFL
https://github.com/OMGDuke/protondb-decky/pull/75
