### ISSUE TITLE
Repeating game controller animation

### ISSUE THREAD

**Issue by Ebantero** [OMGDuke/protondb-decky#80]
For the past couple of weeks I noticed that, when booting up a game on Steam Deck, the controller setup animation will collapse and restart several times over. I believe this happens whenever Steam Cloud is syncing. The problem resolved itself after uninstalling the ProtobDB pluggin. 

Video of the issue attached below:

https://github.com/OMGDuke/protondb-decky/assets/29098234/621e6ec0-3b45-44b4-af07-49c0f993080d

**Comment by Quenary** [comment]
Hello! I have the same issue.
OS version 3.5.19
Decky version 2.12.3
Plugin version 1.0.12-1

**Comment by codethought** [comment]
I think most people are seeing it.. it's so friggin annoying I turned off the pluggin and check back here from time to time to see if anyone has a fix yet..

**Comment by OMGDuke** [comment]
Fixed in #81
