### ISSUE TITLE
ProtonDB indicator is deleted if 'your stuff', 'commnunity' or 'game info' is pressed

### ISSUE THREAD

**Issue by vrman123** [OMGDuke/protondb-decky#9]
### ProtonDB indicator is deleted if 'your stuff', 'commnunity' or 'game info' is pressed
Honestly no idea why this happens, but it sure does.
Not really a huge issue, as it comes back if you in/out but still an issue

**Comment by OMGDuke** [comment]
This should already be fixed on the staging branch. It was because of how I was getting the appId. I'll put this into main in a bit.

**Comment by OMGDuke** [comment]
This is now fixed on main
